### ISSUE TITLE
4o or 4o-mini?

### ISSUE THREAD

**Issue by modim2rpi** [ShujinWu-0814/ALOE#1]
Hi, did you use GPT 4o or GPT 4o mini for the evaluations in the paper? In the paper, you mention 'GPT-4o' as the model, but the code uses 4o-mini. These give very different results.

**Comment by ShujinWu-0814** [comment]
Hi!

Per checking, we did use GPT-4o-mini for the evaluation and make a mistake in our paper. Thank you for pointing out! We will edit it in our paper :)

**Comment by modim2rpi** [comment]
Thank you, closed the issue. Is the code given here the final version used for the paper results or a represention only?

**Comment by ShujinWu-0814** [comment]
It's the final version.
